"""add anniversary + anniversary_channel

Revision ID: 1bfa356ecc71
Revises: d90f7e530ba0
Create Date: 2026-06-26 16:36:26.487970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bfa356ecc71'
down_revision: Union[str, None] = 'd90f7e530ba0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anniversary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('count_label', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'user_id', 'title', 'month', 'day')
    )
    op.create_index(op.f('ix_anniversary_guild_id'), 'anniversary', ['guild_id'], unique=False)
    op.create_index(op.f('ix_anniversary_user_id'), 'anniversary', ['user_id'], unique=False)
    op.create_table('anniversary_channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'channel_id')
    )
    op.create_index(op.f('ix_anniversary_channel_guild_id'), 'anniversary_channel', ['guild_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anniversary_channel_guild_id'), table_name='anniversary_channel')
    op.drop_table('anniversary_channel')
    op.drop_index(op.f('ix_anniversary_user_id'), table_name='anniversary')
    op.drop_index(op.f('ix_anniversary_guild_id'), table_name='anniversary')
    op.drop_table('anniversary')
    # ### end Alembic commands ###
