"""add starboard bypass role

Revision ID: e6f08a9fff33
Revises: 1bfa356ecc71
Create Date: 2026-09-09 10:38:59.888769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6f08a9fff33'
down_revision: Union[str, None] = '1bfa356ecc71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('starboard_config', sa.Column('bypass_role_id', sa.BigInteger(), nullable=True))
    op.add_column('starboard_entry', sa.Column('bypassed_role_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('starboard_entry', 'bypassed_role_id')
    op.drop_column('starboard_config', 'bypass_role_id')
    # ### end Alembic commands ###
