"""baseline_postgres

Revision ID: d90f7e530ba0
Revises: 
Create Date: 2026-06-25 12:11:33.450469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd90f7e530ba0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_excluded_channel',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('guild_id', 'channel_id')
    )
    op.create_table('activity_module_settings',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('inactive_role_id', sa.BigInteger(), nullable=True),
    sa.Column('break_role_id', sa.BigInteger(), nullable=True),
    sa.Column('log_channel', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('guild_id')
    )
    op.create_table('activity_role',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('role_name', sa.String(), nullable=True),
    sa.Column('min', sa.Integer(), nullable=True),
    sa.Column('max', sa.Integer(), nullable=True),
    sa.Column('should_notify', sa.Boolean(), nullable=False),
    sa.Column('rolling_month_window', sa.Integer(), nullable=False),
    sa.Column('grace_period_months', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('guild_id', 'role_id')
    )
    op.create_table('auto_delete_channel_config',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('auto_delete_type', sa.Enum('all', 'photo', 'text', name='autodeletetype'), nullable=False),
    sa.Column('delete_after_minutes', sa.Integer(), nullable=False),
    sa.Column('anchor_message', sa.BigInteger(), nullable=False),
    sa.Column('original_anchor_message', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('guild_id', 'channel_id')
    )
    op.create_table('birthdays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'user_id', 'name')
    )
    op.create_table('guild_config',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('birthday_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('image_deletion_prompts_enabled', sa.Boolean(), nullable=True),
    sa.Column('baby_month_milestone_channel_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('guild_id')
    )
    op.create_table('image_message_to_delete',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('delete_after', sa.DateTime(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('has_failed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('guild_id', 'channel_id', 'message_id')
    )
    op.create_table('poll_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('is_multi_choice', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_question_author_id'), 'poll_question', ['author_id'], unique=False)
    op.create_index(op.f('ix_poll_question_channel_id'), 'poll_question', ['channel_id'], unique=False)
    op.create_index(op.f('ix_poll_question_guild_id'), 'poll_question', ['guild_id'], unique=False)
    op.create_index(op.f('ix_poll_question_message_id'), 'poll_question', ['message_id'], unique=False)
    op.create_table('rolling_message_log',
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_rolling_message_log_author_id'), 'rolling_message_log', ['author_id'], unique=False)
    op.create_index(op.f('ix_rolling_message_log_guild_id'), 'rolling_message_log', ['guild_id'], unique=False)
    op.create_table('santa_participant',
    sa.Column('santa_id', sa.BigInteger(), nullable=False),
    sa.Column('recipient_id', sa.BigInteger(), nullable=False),
    sa.Column('has_shipped', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('santa_id')
    )
    op.create_table('starboard_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('target_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('emoji', sa.String(), nullable=False),
    sa.Column('emoji_id', sa.BigInteger(), nullable=True),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_starboard_config_guild_id'), 'starboard_config', ['guild_id'], unique=False)
    op.create_table('user_activity',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('tracking_started_on', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sent_thirty_day_notice', sa.Boolean(), nullable=False),
    sa.Column('sent_sixty_day_notice', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('guild_id', 'user_id')
    )
    op.create_table('user_channel_settings',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('delete_after', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('guild_id', 'channel_id', 'user_id')
    )
    op.create_table('user_settings',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('image_deletion_prompts_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('guild_id', 'user_id')
    )
    op.create_table('poll_choice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['poll_question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('starboard_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('starboard_config_id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('original_message_id', sa.BigInteger(), nullable=False),
    sa.Column('original_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('posted_message_id', sa.BigInteger(), nullable=True),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('star_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['starboard_config_id'], ['starboard_config.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('starboard_config_id', 'original_message_id')
    )
    op.create_index(op.f('ix_starboard_entry_guild_id'), 'starboard_entry', ['guild_id'], unique=False)
    op.create_index(op.f('ix_starboard_entry_original_message_id'), 'starboard_entry', ['original_message_id'], unique=False)
    op.create_index(op.f('ix_starboard_entry_starboard_config_id'), 'starboard_entry', ['starboard_config_id'], unique=False)
    op.create_table('poll_response',
    sa.Column('choice_id', sa.Integer(), nullable=False),
    sa.Column('respondent_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['choice_id'], ['poll_choice.id'], ),
    sa.PrimaryKeyConstraint('choice_id', 'respondent_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poll_response')
    op.drop_index(op.f('ix_starboard_entry_starboard_config_id'), table_name='starboard_entry')
    op.drop_index(op.f('ix_starboard_entry_original_message_id'), table_name='starboard_entry')
    op.drop_index(op.f('ix_starboard_entry_guild_id'), table_name='starboard_entry')
    op.drop_table('starboard_entry')
    op.drop_table('poll_choice')
    op.drop_table('user_settings')
    op.drop_table('user_channel_settings')
    op.drop_table('user_activity')
    op.drop_index(op.f('ix_starboard_config_guild_id'), table_name='starboard_config')
    op.drop_table('starboard_config')
    op.drop_table('santa_participant')
    op.drop_index(op.f('ix_rolling_message_log_guild_id'), table_name='rolling_message_log')
    op.drop_index(op.f('ix_rolling_message_log_author_id'), table_name='rolling_message_log')
    op.drop_table('rolling_message_log')
    op.drop_index(op.f('ix_poll_question_message_id'), table_name='poll_question')
    op.drop_index(op.f('ix_poll_question_guild_id'), table_name='poll_question')
    op.drop_index(op.f('ix_poll_question_channel_id'), table_name='poll_question')
    op.drop_index(op.f('ix_poll_question_author_id'), table_name='poll_question')
    op.drop_table('poll_question')
    op.drop_table('image_message_to_delete')
    op.drop_table('guild_config')
    op.drop_table('birthdays')
    op.drop_table('auto_delete_channel_config')
    op.drop_table('activity_role')
    op.drop_table('activity_module_settings')
    op.drop_table('activity_excluded_channel')
    # ### end Alembic commands ###
