"""add starboard tables

Revision ID: 44433ddac1b1
Revises: c7a45ca9ec78
Create Date: 2026-06-23 09:34:18.495067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44433ddac1b1'
down_revision: Union[str, None] = 'c7a45ca9ec78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('starboard_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('target_channel_id', sa.Integer(), nullable=False),
    sa.Column('emoji', sa.String(), nullable=False),
    sa.Column('emoji_id', sa.Integer(), nullable=True),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_starboard_config_guild_id'), 'starboard_config', ['guild_id'], unique=False)
    op.create_table('starboard_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('starboard_config_id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('original_message_id', sa.Integer(), nullable=False),
    sa.Column('original_channel_id', sa.Integer(), nullable=False),
    sa.Column('posted_message_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('star_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['starboard_config_id'], ['starboard_config.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('starboard_config_id', 'original_message_id')
    )
    op.create_index(op.f('ix_starboard_entry_guild_id'), 'starboard_entry', ['guild_id'], unique=False)
    op.create_index(op.f('ix_starboard_entry_original_message_id'), 'starboard_entry', ['original_message_id'], unique=False)
    op.create_index(op.f('ix_starboard_entry_starboard_config_id'), 'starboard_entry', ['starboard_config_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_starboard_entry_starboard_config_id'), table_name='starboard_entry')
    op.drop_index(op.f('ix_starboard_entry_original_message_id'), table_name='starboard_entry')
    op.drop_index(op.f('ix_starboard_entry_guild_id'), table_name='starboard_entry')
    op.drop_table('starboard_entry')
    op.drop_index(op.f('ix_starboard_config_guild_id'), table_name='starboard_config')
    op.drop_table('starboard_config')
    # ### end Alembic commands ###
