"""drop anniversary_channel label

Revision ID: 3620457769df
Revises: 1bfa356ecc71
Create Date: 2026-06-26 21:16:48.620602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3620457769df'
down_revision: Union[str, None] = '1bfa356ecc71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anniversary_channel', 'label')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default='' so a downgrade against an already-populated table can
    # backfill the re-added NOT NULL column instead of failing.
    op.add_column('anniversary_channel', sa.Column('label', sa.VARCHAR(), autoincrement=False, nullable=False, server_default=''))
    # ### end Alembic commands ###
