"""Phase 5 — fresh Postgres baseline: table-set contract.

Guards against a model that isn't imported in ``db/__init__.py``. Such a model
would be silently absent from BOTH ``DB.create_all()`` (the test-harness path)
and the autogenerated Alembic baseline, since Alembic only sees what is
registered on ``DB.Model.metadata`` at import time.

The explicit set below is the contract: every persisted table must appear here,
``DB.Model.metadata`` must hold exactly this set, and ``DB.create_all()`` must
build exactly this set. The squashed Postgres baseline is generated from the
same metadata, so keeping these in lockstep keeps the baseline honest.
"""
from sqlalchemy import inspect

import db  # noqa: F401  registers every model on DB.Model.metadata via db/__init__.py
from db import DB

# Every table the bot persists. Adding a model means adding its table here on
# purpose — a missing entry is exactly the "forgot to import it" bug we guard.
EXPECTED_TABLES = {
    'activity_excluded_channel',
    'activity_module_settings',
    'activity_role',
    'anniversary',
    'anniversary_channel',
    'auto_delete_channel_config',
    'birthdays',
    'guild_config',
    'image_message_to_delete',
    'poll_choice',
    'poll_question',
    'poll_response',
    'rolling_message_log',
    'santa_participant',
    'starboard_config',
    'starboard_entry',
    'user_activity',
    'user_channel_settings',
    'user_settings',
}


def test_metadata_tables_match_contract():
    """Every registered model's table is in the contract, and vice versa."""
    assert set(DB.Model.metadata.tables.keys()) == EXPECTED_TABLES


def test_create_all_builds_expected_tables():
    """``DB.create_all()`` (run once by the session ``_schema`` fixture) builds
    exactly the contract tables — the same set the Alembic baseline creates."""
    reflected = set(inspect(DB.engine).get_table_names())
    assert reflected == EXPECTED_TABLES
